---
title: "2000 Outcome Results"
output: pdf_document
---

```{r}
library(rstudioapi)
library(haven)
library(dplyr)
library(ggplot2)
library(readr)
library(measurements)
library(geosphere)
library(tidyr)
library(kableExtra)
```

```{r}
# load preprocessed data
raw_path <- paste0(dirname(getSourceEditorContext()$path), '/data/raw/')
processed_path <- paste0(dirname(getSourceEditorContext()$path), '/data/processed/')
census2000 <- readRDS(paste0(processed_path, 'census2000_clean.Rda'))

# add schoolstart column to be birthyr + 6 (since birth quarter information not available)
census2000 <- census2000 %>% mutate(schoolstart = birthyr+6)
```

# Replicating Figure 5 for 2000s Outcomes

```{r}
# making log hourly wage column and binarizing
census2000 <- census2000 %>% mutate(log_hourlywage = log(hourly_wages))
census2000 <- census2000 %>% mutate(aboveavg_lhw = as.integer(log_hourlywage >= mean(log_hourlywage)))
```

```{r}
avg_cov <- mean(census2000$pred_cov)
low_cov <- census2000 %>% filter(pred_cov <= avg_cov) %>% group_by(schoolstart) %>% summarize(prop_employed = mean(is_working), prop_poverty = mean(in_poverty), prop_abovelhw = mean(aboveavg_lhw))
high_cov <- census2000 %>% filter(pred_cov > avg_cov) %>% group_by(schoolstart) %>% summarize(prop_employed = mean(is_working), prop_poverty = mean(in_poverty), prop_abovelhw = mean(aboveavg_lhw))

low_cov <- gather(low_cov, key = 'category', value = 'low_prop', prop_employed, prop_poverty, prop_abovelhw)
high_cov <- gather(high_cov, key = 'category', value = 'high_prop', prop_employed, prop_poverty, prop_abovelhw)
cov_comparison <- low_cov %>% mutate(high_prop = high_cov$high_prop)
```


```{r}
ggplot(cov_comparison) + geom_col(aes(x = as.factor(schoolstart), y = high_prop-low_prop, fill = category)) + xlab('Expected Year of Beginning School') + ylab('Difference in Proportions') + ggtitle('Comparing Proportions of Different Variables, High vs. Low Coverage') + theme_light() + scale_fill_discrete(name = '', labels = c('Above Average \n Log-Hourly Wage?', 'Is Employed?', 'Is in Poverty?'))
```

# Fitting Regression Models

```{r}
# Subsetting proper data for model fitting
reg_dat <- census2000 %>% select(hsspend_at_four, fs_available, female, 
                                 blacknh, othernh, hispanic, 
                                 full_cty_fips, st_fips, schoolstart, 
                                 preschool1969, in_poverty, is_working, 
                                 aboveavg_lhw, whitenh, pred_cov)
# creating proportions of coverage
reg_dat$pred_cov <- reg_dat$pred_cov/100
```

## Full sample, no fixed effects

```{r}
# pre-allocating the rows of Table 6
row1 <- rep(0, 3)
row2 <- rep(0, 3)
row3 <- rep(0, 3)
row4 <- rep(0, 3)
row5 <- rep(0, 3)
row6 <- rep(0, 3)
```

```{r}
# filling in the first row of the means of at-grade level students
row1[1] <- mean(reg_dat$aboveavg_lhw)
row1[2] <- mean(reg_dat$is_working)
row1[3] <- mean(reg_dat$in_poverty)
```

```{r}
# fitting aggregated cohort regression models for each demographic group
linear_mod1 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])
```

```{r}
# fitting disaggregated cohort models for each demographic subgroup

# creating cohort group indicators
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

# doing the fits
linear_mod2 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 6 for 2000s outcomes results
tab6_df <- rbind(row1, row2, row3, row4, row5, row6)
tab6_df <- round(data.frame(tab6_df), 4)
colnames(tab6_df) <- c('Above avg. lhw', 'Employed', 'Poverty')
rownames(tab6_df) <- c('Proportion of:', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab6_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups.') %>% kable_classic()
```

## Full sample, only cohort level fixed effects

```{r}
# fitting aggregated cohort regression models for each demographic group
linear_mod1 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])
```

```{r}
# fitting disaggregated cohort regression model for each demographic subgroup

# creating cohort group indicators
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

# doing the fits
linear_mod2 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 6

tab6_df <- rbind(row1, row2, row3, row4, row5, row6)
tab6_df <- round(data.frame(tab6_df), 4)
colnames(tab6_df) <- c('Above avg. lhw', 'Employed', 'Poverty')
rownames(tab6_df) <- c('Proportion of:', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab6_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups.') %>% kable_classic()
```

## All fixed effects, state subsample

```{r}
# subsetting by the proper states
reg_dat <- reg_dat %>% filter(st_fips %in% c('48', '06', '12', '36'))

# filling in the first row of the means of at-grade level students
row1[1] <- mean(reg_dat$aboveavg_lhw)
row1[2] <- mean(reg_dat$is_working)
row1[3] <- mean(reg_dat$in_poverty)
```

```{r}
# fitting the aggregated cohort models for each demographic subgroup
linear_mod1 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + female + 
                       othernh + hispanic + preschool1969:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])
```

```{r}
# fitting the disaggregated cohort model for each demographic subgroup

# creating cohort group indicators
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

# doing the fits
linear_mod2 <- glm(aboveavg_lhw ~ hsspend_at_four + fs_available + female + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(is_working ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(in_poverty ~ hsspend_at_four + fs_available + blacknh + 
                       othernh + hispanic + preschool6768:pred_cov + female +
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(schoolstart):factor(st_fips) + factor(full_cty_fips), 
                     family = 'gaussian', data = reg_dat)
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 6

tab6_df <- rbind(row1, row2, row3, row4, row5, row6)
tab6_df <- round(data.frame(tab6_df), 4)
colnames(tab6_df) <- c('Above avg. lhw', 'Employed', 'Poverty')
rownames(tab6_df) <- c('Proportion of:', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab6_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups.') %>% kable_classic()
```