---
title: "1980 Outcome Results"
output: pdf_document
---
```{r}
library(rstudioapi)
library(haven)
library(dplyr)
library(ggplot2)
library(readr)
library(measurements)
library(geosphere)
library(tidyr)
library(kableExtra)
```

```{r}
# load preprocessed data
raw_path <- paste0(dirname(getSourceEditorContext()$path), '/data/raw/')
processed_path <- paste0(dirname(getSourceEditorContext()$path), '/data/processed/')
census1980 <- readRDS(paste0(processed_path, 'census1980_clean.Rda'))
```

```{r}
# replicating Figure 5 from paper

avg_cov <- mean(census1980$pred_cov)
low_cov <- census1980 %>% filter(pred_cov <= avg_cov) %>% group_by(schoolstart) %>% summarize(prop_gradelvl = mean(at_gradelvl))
high_cov <- census1980 %>% filter(pred_cov > avg_cov) %>% group_by(schoolstart) %>% summarize(prop_gradelvl = mean(at_gradelvl))
cov_comparison <- low_cov %>% rename(low = prop_gradelvl) %>% mutate(high = high_cov$prop_gradelvl)
cov_comparison <- cov_comparison %>% mutate(diff = high - low) 
cov_comparison$diff1960 <- cov_comparison$diff - cov_comparison$diff[1]
ggplot(cov_comparison) + geom_col(aes(x = as.factor(schoolstart), y = diff1960)) + xlab('Expected Year of Beginning School') + ylab('Difference in Proportions between \n High and Low Coverage Areas') + ggtitle('Comparing Proportions of At-Grade Level Children with High vs. Low Coverage') + theme_light()

```
# Fitting Regression Models

```{r}
# Subsetting proper data for model fitting
reg_dat <- census1980 %>% select(hsspend_at_four, fs_available, female, momhsdrop,
                                 momhsgrad, blacknh, othernh, hispanic, 
                                 full_cty_fips, stname, schoolstart, 
                                 preschool1969, pred_cov, at_gradelvl, whitenh)
# convert to proportions for fitting
reg_dat$pred_cov <- reg_dat$pred_cov/100
reg_dat <- reg_dat %>% mutate(preschool_cov = preschool1969*pred_cov)
```

## Full sample, no fixed effects

Replicating table 4, but for models on the full sample and no fixed effects

```{r}
# pre-allocating the rows of Table 4
row1 <- rep(0, 6)
row2 <- rep(0, 6)
row3 <- rep(0, 6)
row4 <- rep(0, 6)
row5 <- rep(0, 6)
row6 <- rep(0, 6)
```

```{r}
# filling in the first row of the means of at-grade level students
row1[1] <- mean(reg_dat$at_gradelvl)
row1[2] <- mean(reg_dat %>% filter(female == 0) %>% select(at_gradelvl) %>% unlist())
row1[3] <- mean(reg_dat %>% filter(female == 1) %>% select(at_gradelvl) %>% unlist())
row1[4] <- mean(reg_dat %>% filter(whitenh == 1) %>% select(at_gradelvl) %>% unlist())
row1[5] <- mean(reg_dat %>% filter(blacknh == 1) %>% select(at_gradelvl) %>% unlist())
row1[6] <- mean(reg_dat %>% filter(hispanic == 1) %>% select(at_gradelvl) %>% unlist())
```

```{r}
# fitting aggregate cohort model with no fixed effects, for each demographic group

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(female == 0))
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(female == 1))
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop + female +
                       momhsgrad + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row2[4] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1))

row2[5] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row2[6] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

```

```{r}
# fitting the more disaggregated cohort model with no fixed effects

# creating indicators for each cohort group
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

# beginning fits
linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(female == 0))
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(female == 1))
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row3[4] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1))
row3[5] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov, 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row3[6] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 4, with coefficients presented

tab4_df <- rbind(row1, row2, row3, row4, row5, row6)
tab4_df <- round(data.frame(tab4_df), 4)
colnames(tab4_df) <- c('All', 'Boys', 'Girls', 'White, NH', 'Black, NH', 'Hispanic')
rownames(tab4_df) <- c('Proportion of at-grade level', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab4_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups.') %>% kable_classic()
```

## Full sample, only cohort-level fixed effects

```{r}
# fitting aggregate cohort models for each demographic subgroup
linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov + factor(schoolstart), family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov + factor(schoolstart), family = 'gaussian', data = reg_dat %>% filter(female == 0))
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov+ factor(schoolstart),family = 'gaussian', data = reg_dat %>% filter(female == 1))
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop + female +
                       momhsgrad + preschool1969:pred_cov+ factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row2[4] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov + factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1))
row2[5] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov+ factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row2[6] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])
```

```{r}
# fitting disaggregated cohort models for each demographic subgroup

# creating cohort level indicators
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov+ 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 0))
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov+ 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 1))
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov+ 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row3[4] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov+ 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1))
row3[5] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov+ 
                       factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row3[6] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 4, with coefficients

tab4_df <- rbind(row1, row2, row3, row4, row5, row6)
tab4_df <- round(data.frame(tab4_df), 4)
colnames(tab4_df) <- c('All', 'Boys', 'Girls', 'White, NH', 'Black, NH', 'Hispanic')
rownames(tab4_df) <- c('Proportion of at-grade level', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab4_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups.') %>% kable_classic()
```

## All fixed effects, state subsample

```{r}
# subsetting by the proper states
reg_dat <- reg_dat %>% filter(stname %in% c('FL', 'NY', 'CA', 'TX'))

# filling in the first row of the means of at-grade level students
row1[1] <- mean(reg_dat$at_gradelvl)
row1[2] <- mean(reg_dat %>% filter(female == 0) %>% select(at_gradelvl) %>% unlist())
row1[3] <- mean(reg_dat %>% filter(female == 1) %>% select(at_gradelvl) %>% unlist())
row1[4] <- mean(reg_dat %>% filter(whitenh == 1) %>% select(at_gradelvl) %>% unlist())
row1[5] <- mean(reg_dat %>% filter(blacknh == 1) %>% select(at_gradelvl) %>% unlist())
row1[6] <- mean(reg_dat %>% filter(hispanic == 1) %>% select(at_gradelvl) %>% unlist())
```

```{r}
# fitting aggregate cohort models for each demographic subgroup
linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row2[1] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 0))
row2[2] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 1))
row2[3] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop + female +
                       momhsgrad + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row2[4] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1))

row2[5] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])

linear_mod1 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool1969:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row2[6] <- as.numeric(linear_mod1$coefficients['preschool1969:pred_cov'])
```

```{r}
# fitting disgaggregated cohort model for each demographic subgroup
reg_dat <- reg_dat %>% mutate(preschool6768 = as.integer(reg_dat$schoolstart >= 1967 & reg_dat$schoolstart <= 1968)) %>%
  mutate(preschool69 = as.integer(reg_dat$schoolstart == 1969)) %>%
  mutate(preschool7072 = as.integer(reg_dat$schoolstart >= 1970 & reg_dat$schoolstart <= 1972)) %>%
  mutate(preschool7374 = as.integer(reg_dat$schoolstart >= 1973 & reg_dat$schoolstart <= 1974))

# doing the fits
linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat)
row3[1] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[1] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 0))
row3[2] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[2] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + momhsdrop +
                       momhsgrad + blacknh + othernh + hispanic + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(female == 1))
row3[3] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[3] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(whitenh == 1))
row3[4] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[4] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(blacknh == 1)) 
row3[5] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[5] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])

linear_mod2 <- glm(at_gradelvl ~ hsspend_at_four + fs_available + female + momhsdrop +
                       momhsgrad + preschool6768:pred_cov + 
                       preschool69:pred_cov + preschool7072:pred_cov + preschool7374:pred_cov + factor(full_cty_fips) + factor(stname):factor(schoolstart), 
                     family = 'gaussian', data = reg_dat %>% filter(hispanic == 1))
row3[6] <- as.numeric(linear_mod2$coefficients['preschool6768:pred_cov'])
row4[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool69'])
row5[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7072'])
row6[6] <- as.numeric(linear_mod2$coefficients['pred_cov:preschool7374'])
```

```{r}
# making Table 4

tab4_df <- rbind(row1, row2, row3, row4, row5, row6)
tab4_df <- round(data.frame(tab4_df), 4)
colnames(tab4_df) <- c('All', 'Boys', 'Girls', 'White, NH', 'Black, NH', 'Hispanic')
rownames(tab4_df) <- c('Proportion of at-grade level', 
                       'Preschool post-1969 x coverage rate',
                       'Coverage rate x 67-68',
                       'Coverage rate x 69',
                       'Coverage rate x 70-72',
                       'Coverage rate x 73-74')

kable(tab4_df, caption = 'Regression coefficients of variable capturing causal effect of interest for different subgroups, in state subsample.') %>% kable_classic()
```
